// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDXw8u-up1oTLVfzLZyCIFD3BmlWdohOI',
    appId: '1:150499881272:web:07cba574d9a6fc536751cd',
    messagingSenderId: '150499881272',
    projectId: 'taskmate-7f167',
    authDomain: 'taskmate-7f167.firebaseapp.com',
    storageBucket: 'taskmate-7f167.firebasestorage.app',
    measurementId: 'G-9PWQW7CXZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVtD7l0s2PWlA6MXmiroH37Iz42OHrqV8',
    appId: '1:150499881272:android:c2744436ddc91c226751cd',
    messagingSenderId: '150499881272',
    projectId: 'taskmate-7f167',
    storageBucket: 'taskmate-7f167.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjTTaPqTXdlnTE7c4CS9RdFjc5_jJokBw',
    appId: '1:150499881272:ios:0ae42f9ca6f54f9a6751cd',
    messagingSenderId: '150499881272',
    projectId: 'taskmate-7f167',
    storageBucket: 'taskmate-7f167.firebasestorage.app',
    iosBundleId: 'com.example.taskmateApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjTTaPqTXdlnTE7c4CS9RdFjc5_jJokBw',
    appId: '1:150499881272:ios:0ae42f9ca6f54f9a6751cd',
    messagingSenderId: '150499881272',
    projectId: 'taskmate-7f167',
    storageBucket: 'taskmate-7f167.firebasestorage.app',
    iosBundleId: 'com.example.taskmateApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDXw8u-up1oTLVfzLZyCIFD3BmlWdohOI',
    appId: '1:150499881272:web:07cba574d9a6fc536751cd',
    messagingSenderId: '150499881272',
    projectId: 'taskmate-7f167',
    authDomain: 'taskmate-7f167.firebaseapp.com',
    storageBucket: 'taskmate-7f167.firebasestorage.app',
    measurementId: 'G-9PWQW7CXZE',
  );
}
